name: Release APK

permissions:
    contents: write
    issues: write 
    pull-requests: write     

on:
    push:
        branches: 
            - 'master'
    workflow_dispatch:        

jobs:
    release:
        name: Release APK
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Install Node
          uses: actions/setup-node@v5
          with:
            node-version: 'lts/*'
        
        - name: package-lock
          run: |
            if [ ! -f package-lock.json ]; then
              npm install --package-lock-only
            fi    

        - name: NPM clean install
          run: npm install --save-dev semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github
        
        - name: Uninstall NPM Publish
          run: npm uninstall @semantic-release/npm

        - name: Semantic Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          run: npx semantic-release 
          
        - name: Get generated tag
          id: get_version
          run: |
            VERSION=$(git describe --tags --abbrev=0)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'jetbrains'
            java-version: '21'
            cache: 'gradle'

        - name: Change gradle permission
          run: chmod +x ./gradlew

        - name: Bundle the app
          run: ./gradlew assemble

        - name: Move Release APK
          run: mv ./app/build/outputs/apk/release/*release*.apk ./release.apk

        - name: Upload apk
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ env.VERSION }}
            file: ./release.apk
            asset_name: release-${{ env.VERSION }}.apk


